import {test,expect} from '@playwright/test'
import ExcelJS from 'exceljs'
async function accounts(rows:unknown[][]){const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('账号导入');sheet.addRow(['账号','姓名','角色','初始密码']);sheet.addRows(rows);return Buffer.from(await book.xlsx.writeBuffer())}
test('administrator downloads account template, previews import and corrects duplicate rows',async({page})=>{
  await page.goto('/project-system.html')
  await page.getByLabel('账号',{exact:true}).fill('admin')
  await page.getByLabel('密码',{exact:true}).fill('project-browser-password-123')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await page.getByRole('button',{name:'系统管理',exact:true}).click()
  await expect(page.getByRole('combobox',{name:'角色',exact:true}).locator('option')).toHaveText(['系统管理员','导师','学生','只读访客'])
  const section=page.locator('.account-import')
  const download=page.waitForEvent('download');await section.getByRole('button',{name:'下载导入模板'}).click()
  const templateFile=await download;expect(templateFile.suggestedFilename()).toBe('账号批量导入模板.xlsx');const templateBook=new ExcelJS.Workbook();await templateBook.xlsx.readFile((await templateFile.path())!);expect(templateBook.getWorksheet('账号导入')!.getRow(1).values).toEqual([undefined,'账号','姓名','角色','初始密码']);expect(templateBook.getWorksheet('账号导入')!.getColumn(4).numFmt).toBe('@')
  await section.getByRole('button',{name:'批量导入',exact:true}).click()
  
  const good=['excel-browser@example.cc','导入浏览器教师','','excel-password-123']
  const input=section.getByLabel('选择导入文件');await input.setInputFiles({name:'formula.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await accounts([[{formula:'1+1'},'公式账号','导师','excel-password-123']])});await expect(page.getByRole('alert')).toContainText('不能使用公式')
  await input.setInputFiles({name:'accounts.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await accounts([good,['ADMIN','另一教师','导师','excel-password-123']])})
  await expect(section.getByRole('alert')).toContainText('第3行')
  await expect(section.getByRole('button',{name:/确认导入/})).toBeDisabled()
  await expect(section).not.toContainText('excel-password-123')
  await input.setInputFiles({name:'accounts.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await accounts([good])})
  await expect(section).toContainText('校验通过，确认后创建')
  await section.getByRole('button',{name:'确认导入1个账号'}).click()
  await expect(section.getByRole('status')).toContainText('已成功导入1个账号')
  await expect(page.locator('tr').filter({hasText:'excel-browser@example.cc'})).toContainText('导师')
  await section.getByLabel('选择导入文件').setInputFiles({name:'duplicate.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await accounts([good])})
  await expect(section.getByRole('alert')).toContainText('已存在')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/projects/account-import-mobile.png',fullPage:true})
})
test('administrator edits member type inline and the name persists after refresh',async({page})=>{
  await page.goto('/project-system.html')
  await page.getByLabel('账号',{exact:true}).fill('admin')
  await page.getByLabel('密码',{exact:true}).fill('project-browser-password-123')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  await page.getByRole('button',{name:'系统管理',exact:true}).click()
  await page.getByRole('button',{name:'成员类型',exact:true}).click()
  const row=page.locator('.dictionary-row').filter({hasText:'专业教师'})
  await row.getByRole('button',{name:'修改名称',exact:true}).click()
  await page.getByLabel('成员类型名称',{exact:true}).fill('专业研究人员')
  await page.getByRole('button',{name:'保存名称',exact:true}).click()
  await expect(page.locator('.dictionary-row').filter({hasText:'专业研究人员'})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'成员类型',exact:true}).click()
  const renamed=page.locator('.dictionary-row').filter({hasText:'专业研究人员'})
  await expect(renamed).toBeVisible()
  await renamed.getByRole('button',{name:'修改名称',exact:true}).click()
  await page.getByLabel('成员类型名称',{exact:true}).fill('专业教师')
  await page.getByRole('button',{name:'保存名称',exact:true}).click()
  await expect(row).toBeVisible()
})
