import { test,expect } from '@playwright/test'
test('gantt groups milestone tasks and descendants, positions planned and actual dates, preserves unassigned tasks and mobile scrolling',async({page})=>{
 await page.goto('/project-system.html');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('project-browser-password-123');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeVisible();
 const data=await page.evaluate(async()=>{const s=await fetch('/api/session').then(r=>r.json());async function call(path:string,body:unknown){const r=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());return r.json()}
 let p=await call('/pm/projects',{title:'里程碑分组甘特验证'});const base={assigneeId:s.user.id,start:'2026-09-01',due:'2026-09-20',state:'已完成',progress:100};p=await call(`/pm/projects/${p.id}/tasks`,{...base,title:'关联父任务'});const parent=p.tasks[0];p=await call(`/pm/projects/${p.id}/tasks`,{...base,title:'旗下子任务',parentId:parent.id,start:'2026-09-10',due:'2026-09-15'});const child=p.tasks.find((t:{title:string})=>t.title==='旗下子任务');p=await call(`/pm/projects/${p.id}/tasks`,{...base,title:'独立任务',start:'2026-10-01',due:'2026-10-20',state:'进行中',progress:60});
 p=await call(`/pm/projects/${p.id}/milestones`,{title:'阶段一验收',planned:'2026-09-25',actual:'2026-09-26',state:'已完成',progress:100,taskIds:[parent.id]});const first=p.milestones[0];p=await call(`/pm/projects/${p.id}/milestones`,{title:'阶段二交付',planned:'2026-10-25',taskIds:[parent.id,child.id],dependsOn:first.id});const second=p.milestones.find((m:{title:string})=>m.title==='阶段二交付');p=await call(`/pm/projects/${p.id}/milestones`,{title:'空任务节点',planned:'2026-10-30'});return {id:p.id,parent:parent.id,child:child.id,first:first.id,second:second.id}});
 await page.goto(`/project-system.html?project=${data.id}&group=project_gantt`);const table=page.getByRole('table',{name:'项目里程碑与任务甘特图',exact:true}),first=table.locator(`tbody[data-milestone-id="${data.first}"]`),second=table.locator(`tbody[data-milestone-id="${data.second}"]`),unassigned=table.locator('tbody[data-milestone-id="unassigned"]');await expect(first.locator('.pg-task')).toHaveCount(2);await expect(first).toContainText('旗下子任务');await expect(second.locator('.pg-task')).toHaveCount(2);await expect(unassigned.locator('.pg-task')).toHaveCount(1);await expect(unassigned).toContainText('独立任务');await expect(unassigned).not.toContainText('旗下子任务');await expect(table.locator('.pg-empty-group')).toContainText('尚未关联任务');await expect(first.getByLabel('阶段一验收计划日期 2026-09-25',{exact:true})).toBeVisible();await expect(first.getByLabel('阶段一验收实际完成日期 2026-09-26',{exact:true})).toBeVisible();await expect(page.locator('.pg-axis')).toContainText('2026-09-01');await expect(page.locator('.pg-axis')).toContainText('2026-10-30');
 const styles=await table.locator('.gantt-bar').evaluateAll(nodes=>nodes.map(n=>({left:parseFloat((n as HTMLElement).style.left),width:parseFloat((n as HTMLElement).style.width)})));expect(styles.every(s=>Number.isFinite(s.left)&&Number.isFinite(s.width)&&s.left>=0&&s.width>0&&s.left+s.width<=100.001)).toBe(true);await expect(first.locator('.gantt-bar').first()).toHaveAttribute('style',/left: 0%; width: 33/);await page.screenshot({path:'test-results/projects/gantt-milestones-desktop.png',animations:'disabled'});
 await first.getByRole('button',{name:/阶段一验收/}).click();await expect(first.locator('.pg-task')).toHaveCount(0);await expect(second.locator('.pg-task')).toHaveCount(2);await expect(first.locator('.pg-marker')).toHaveCount(2);await page.getByRole('button',{name:'收起全部',exact:true}).click();await expect(table.locator('.pg-task')).toHaveCount(0);await page.getByRole('button',{name:'展开全部',exact:true}).click();await expect(table.locator('.pg-task')).toHaveCount(5);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/projects/gantt-milestones-mobile.png',animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const scroller=page.locator('.pg-scroll');expect(await scroller.evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);await scroller.evaluate(el=>el.scrollLeft=el.scrollWidth);await expect(first.getByRole('button',{name:/阶段一验收/})).toBeVisible();await page.reload();await expect(table.locator('.pg-task')).toHaveCount(5)
})
