import ExcelJS from 'exceljs'
async function excelText(path:string){const book=new ExcelJS.Workbook();await book.xlsx.readFile(path);return JSON.stringify(book.worksheets[0]!.getSheetValues())}
import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
const password='project-browser-password-123'
async function login(page:Page,account='admin'){
 await page.goto('/project-system.html');await page.getByLabel('账号',{exact:true}).fill(account);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeAttached()
}
async function call(page:Page,path:string,method='GET',data?:unknown){return page.evaluate(async({path,method,data})=>{const s=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()},{path,method,data})}
test('person hours summarize a project or all visible projects by total, calendar week and month',async({page,browser})=>{
 await login(page);const me=await call(page,'/session');const a=await call(page,'/users','POST',{account:'summary-person-a',name:'统计教师甲',role:'导师',password}),b=await call(page,'/users','POST',{account:'summary-person-b',name:'统计教师乙',role:'导师',password}),zero=await call(page,'/users','POST',{account:'summary-person-zero',name:'零工时教师',role:'导师',password});
 async function project(title:string,users:string[]){let p=await call(page,'/pm/projects','POST',{title,members:users.map(userId=>({userId,role:'项目成员'}))});return call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'统计研究任务',assigneeId:me.user.id,start:'2026-09-01',due:'2026-12-31',state:'进行中',progress:20})}
 const p=await project('工时统计项目甲',[a.id,zero.id]),q=await project('工时统计项目乙',[a.id,b.id]);await project('非参与项目不应可见',[]);
 async function record(project:{id:string;tasks:{id:string}[]},userId:string,start:string,end:string){await call(page,`/pm/projects/${project.id}/time-entries`,'POST',{taskId:project.tasks[0]!.id,userId,start,end,note:'统计验证'})}
 await record(p,a.id,'2026-09-30T23:30','2026-10-01T01:00');await record(p,a.id,'2026-10-04T23:00','2026-10-05T01:00');await record(p,a.id,'2026-09-01T10:00','2026-09-01T12:00');await record(q,a.id,'2026-10-02T10:00','2026-10-02T12:00');await record(q,b.id,'2026-10-02T10:00','2026-10-02T11:00');
 await page.goto(`/project-system.html?project=${p.id}&group=project_timesheets`);const summary=page.getByRole('region',{name:'人员工时统计',exact:true}),table=page.getByRole('table',{name:'人员工时汇总',exact:true});await summary.getByLabel('统计周',{exact:true}).fill('2026-10-02');await summary.getByLabel('统计月',{exact:true}).fill('2026-10');await summary.getByLabel('统计人员',{exact:true}).selectOption(a.id);let row=table.locator('tbody tr');await expect(row).toHaveCount(1);await expect(row.locator('td').nth(1)).toContainText('05:30');await expect(row.locator('td').nth(2)).toContainText('02:30');await expect(row.locator('td').nth(3)).toContainText('03:00');await expect(summary).toContainText('2026-09-28 — 2026-10-04');await page.getByLabel('搜索工时记录').fill('不存在的备注');await expect(page.getByRole('table',{name:'工时记录',exact:true}).locator('tbody tr')).toHaveCount(0);await expect(row.locator('td').nth(1)).toContainText('05:30');await summary.getByLabel('统计人员',{exact:true}).selectOption(zero.id);await expect(table).toContainText('00:00');await summary.getByLabel('统计人员',{exact:true}).selectOption(a.id);
 await summary.getByLabel('统计周',{exact:true}).fill('2026-10-05');await expect(row.locator('td').nth(2)).toContainText('01:00');await summary.getByLabel('统计月',{exact:true}).fill('2026-09');await expect(row.locator('td').nth(3)).toContainText('02:30');
 await page.goto('/project-system.html?view=timesheets');await summary.getByLabel('统计周',{exact:true}).fill('2026-10-02');await summary.getByLabel('统计月',{exact:true}).fill('2026-10');await summary.getByLabel('统计人员',{exact:true}).selectOption(a.id);row=table.locator('tbody tr');await expect(row.locator('td').nth(1)).toHaveText('2');await expect(row.locator('td').nth(2)).toContainText('07:30');await expect(row.locator('td').nth(3)).toContainText('04:30');await expect(row.locator('td').nth(4)).toContainText('05:00');const promise=page.waitForEvent('download');await summary.getByRole('button',{name:'导出统计',exact:true}).click();const download=await promise,csv=await excelText((await download.path())!);expect(csv).toContain('统计教师甲');expect(csv).toContain('07:30');expect(csv).toContain('04:30');expect(csv).toContain('05:00');expect(csv).not.toContain('统计教师乙');await summary.getByLabel('统计项目范围').selectOption(q.id);await expect(row.locator('td').nth(2)).toContainText('02:00');await summary.getByLabel('统计人员',{exact:true}).selectOption(b.id);await expect(row.locator('td').nth(2)).toContainText('01:00');await summary.getByRole('button',{name:'重置统计',exact:true}).click();await summary.getByLabel('统计人员',{exact:true}).selectOption(a.id);await page.screenshot({path:'test-results/projects/time-summary-desktop.png',animations:'disabled'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/projects/time-summary-mobile.png',animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const context=await browser.newContext();const member=await context.newPage();try{await login(member,'summary-person-a');await member.goto('/project-system.html?view=timesheets');const s=member.getByRole('region',{name:'人员工时统计',exact:true});await expect(s.getByLabel('统计项目范围').locator('option')).toHaveCount(3);await expect(s.getByLabel('统计项目范围')).not.toContainText('非参与项目不应可见');await s.getByLabel('统计人员',{exact:true}).selectOption(a.id);await expect(member.getByRole('table',{name:'人员工时汇总',exact:true})).toContainText('07:30')}finally{await context.close()}
})
test('timesheet creation, cross-day duration, editing, overlap validation, filters, Excel and deletion',async({page})=>{
 await login(page);const me=await call(page,'/session');let p=await call(page,'/pm/projects','POST',{title:'工时交互验证项目'});p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'工时验证任务',assigneeId:me.user.id,start:'2026-09-01',due:'2026-12-31',state:'进行中',progress:20});
 await page.goto(`/project-system.html?project=${p.id}&group=project_timesheets`);const table=page.getByRole('table',{name:'工时记录',exact:true});const create=page.getByRole('button',{name:'＋ 工时记录',exact:true});await expect(page.getByRole('heading',{name:'工时表',exact:true})).toHaveCount(0);await expect(page.locator('.summary-actions button')).toHaveText(['＋ 工时记录','导出统计']);await create.click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(create).toBeFocused();
 async function fill(start:string,end:string,note:string){const d=page.getByRole('dialog');await d.getByLabel('开始时间',{exact:true}).fill(start);await d.getByLabel('结束时间',{exact:true}).fill(end);await d.getByLabel('备注',{exact:true}).fill(note);return d}
 await create.click();let d=await fill('2026-09-29T10:30','2026-09-29T12:00','=SUM(1,2)讨论会');await d.getByLabel('工时表标签',{exact:true}).fill('会议、科研');await expect(d).toContainText('01:30（1.5小时）');await d.getByRole('button',{name:'保存工时',exact:true}).click();await expect(d).toHaveCount(0);await expect(table).toContainText('01:30');await expect(table).toContainText('会议');await expect(table).toContainText('科研');
 await create.click();d=await fill('2026-09-29T11:30','2026-09-29T13:00','重叠记录');await d.getByRole('button',{name:'保存工时',exact:true}).click();await expect(d.getByRole('alert')).toContainText('重叠');await fill('2026-09-29T23:30','2026-09-30T01:00','跨日研究');await d.getByRole('button',{name:'保存工时',exact:true}).click();await expect(d).toHaveCount(0);await expect(table.locator('tbody tr')).toHaveCount(2);await expect(page.locator('.timesheet-footer')).toContainText('03:00（3小时）');
 await page.reload();await expect(table.locator('tbody tr')).toHaveCount(2);const row=table.locator('tbody tr').filter({hasText:'讨论会'});await row.getByRole('button',{name:'编辑',exact:true}).click();d=await fill('2026-09-29T10:00','2026-09-29T12:00','=SUM(1,2)讨论会');await d.getByRole('button',{name:'保存工时',exact:true}).click();await expect(d).toHaveCount(0);await expect(row).toContainText('02:00');await page.screenshot({path:'test-results/projects/timesheet-desktop.png'});
 await page.getByRole('button',{name:'筛选',exact:true}).click();await page.getByLabel('工时筛选开始日期').fill('2026-09-30');await expect(table.locator('tbody tr')).toHaveCount(1);await expect(table).toContainText('跨日研究');await page.getByRole('button',{name:'清空',exact:true}).click();await page.getByLabel('搜索工时记录').fill('讨论会');await expect(table.locator('tbody tr')).toHaveCount(1);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出',exact:true}).click();const download=await downloadPromise;const csv=await excelText((await download.path())!);expect(csv).toContain("=SUM(1,2)讨论会");expect(csv).toContain('02:00');expect(csv).not.toContain('跨日研究');
 await page.getByLabel('搜索工时记录').fill('');await page.goto('/project-system.html?view=timesheets');await expect(table).toContainText('工时交互验证项目');await page.getByRole('button',{name:'筛选',exact:true}).click();await page.getByLabel('工时项目筛选').selectOption(p.id);await expect(table.locator('tbody tr')).toHaveCount(2);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/projects/timesheet-mobile.png',animations:'disabled'});await page.setViewportSize({width:1440,height:1050});const cross=table.locator('tbody tr').filter({hasText:'跨日研究'});await cross.getByRole('button',{name:'删除',exact:true}).click();await cross.getByRole('button',{name:'确认删除',exact:true}).click();await expect(cross).toHaveCount(0);await page.reload();await expect(table.locator('tbody tr').filter({hasText:'跨日研究'})).toHaveCount(0)
 for(let i=0;i<11;i++){const hour=String(i).padStart(2,'0');await call(page,`/pm/projects/${p.id}/time-entries`,'POST',{taskId:p.tasks[0].id,start:`2026-10-03T${hour}:00`,end:`2026-10-03T${hour}:30`,note:`分页记录${i}`})}
 await page.reload();await page.getByRole('button',{name:'筛选',exact:true}).click();await page.getByLabel('工时项目筛选').selectOption(p.id);await page.getByLabel('工时每页条数').selectOption('10');await expect(table.locator('tbody tr')).toHaveCount(10);await page.getByRole('button',{name:'下一页',exact:true}).click();await expect(table.locator('tbody tr')).toHaveCount(2);await page.getByLabel('搜索工时记录').fill('讨论会');await expect(table.locator('tbody tr')).toHaveCount(1);await expect(page.locator('.timesheet-footer')).toContainText('1 / 1')
})
test('project participant can record their own sessions and cannot edit others',async({page,browser})=>{
 await login(page);const me=await call(page,'/session');const member=await call(page,'/users','POST',{account:'hours-member',name:'工时参与教师',role:'导师',password});let p=await call(page,'/pm/projects','POST',{title:'工时权限验证项目',members:[{userId:member.id,role:'项目成员'}]});p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'权限验证任务',assigneeId:me.user.id,start:'2026-09-01',due:'2026-12-31',state:'待开始',progress:0});await call(page,`/pm/projects/${p.id}/time-entries`,'POST',{taskId:p.tasks[0].id,start:'2026-10-02T10:00',end:'2026-10-02T11:00',note:'负责人工作'});
 const context=await browser.newContext();const memberPage=await context.newPage();try{await login(memberPage,'hours-member');await memberPage.goto(`/project-system.html?project=${p.id}&group=project_timesheets`);const table=memberPage.getByRole('table',{name:'工时记录',exact:true});const ownerRow=table.locator('tbody tr').filter({hasText:'负责人工作'});await expect(ownerRow.getByRole('button')).toHaveCount(0);await memberPage.getByRole('button',{name:'＋ 工时记录',exact:true}).click();const d=memberPage.getByRole('dialog');await expect(d.getByLabel('工时成员',{exact:true})).toBeDisabled();await expect(d.getByLabel('工时成员',{exact:true})).toHaveValue(member.id);await d.getByLabel('开始时间',{exact:true}).fill('2026-10-02T10:00');await d.getByLabel('结束时间',{exact:true}).fill('2026-10-02T10:45');await d.getByLabel('备注',{exact:true}).fill('参与教师工作');await d.getByRole('button',{name:'保存工时',exact:true}).click();await expect(d).toHaveCount(0);const ownRow=table.locator('tbody tr').filter({hasText:'参与教师工作'});await expect(ownRow).toContainText('00:45');await expect(ownRow.getByRole('button',{name:'编辑',exact:true})).toBeVisible()}finally{await context.close()}
})
