import {test,expect,type Page} from '@playwright/test'
async function call(page:Page,path:string,method='GET',data?:unknown){return page.evaluate(async({path,method,data})=>{const s=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()},{path,method,data})}
test('merged milestone/task trees collapse and task participants persist and chronological project process lists tasks and milestones',async({page})=>{
 await page.goto('/project-system.html');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill('project-browser-password-123');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeAttached();
 const s=await call(page,'/session');let p=await call(page,'/pm/projects','POST',{title:'合并与记录浏览器项目',start:'2026-09-01',end:'2026-12-31'});
 const participant=await call(page,'/users','POST',{account:'process-participant',name:'过程参与人员',role:'学生',password:'project-browser-password-123'});p=await call(page,`/pm/projects/${p.id}`,'PUT',{...p,members:[{userId:participant.id,role:'项目成员'}]});
 p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'合并父任务',assigneeId:s.user.id,start:'2026-09-01',due:'2026-10-01',state:'进行中',progress:20});const parent=p.tasks[0];
 p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'合并子任务',assigneeId:s.user.id,start:'2026-09-02',due:'2026-09-30',parentId:parent.id,state:'待开始',progress:0});
 p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'独立任务',assigneeId:s.user.id,start:'2026-09-04',due:'2026-10-01',state:'待开始',progress:0});
 p=await call(page,`/pm/projects/${p.id}/milestones`,'POST',{title:'合并里程碑',planned:'2026-10-01',taskIds:[parent.id],state:'进行中',progress:20});
 p=await call(page,`/pm/projects/${p.id}/time-entries`,'POST',{taskId:parent.id,userId:s.user.id,start:'2026-09-03T09:00',end:'2026-09-03T10:30',note:'',tags:[]});
 await page.goto(`/project-system.html?project=${p.id}&group=project_milestones`);
 await expect(page.getByRole('tab',{name:'里程碑与任务',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByRole('tab',{name:'里程碑',exact:true})).toHaveCount(0);
 await expect(page.getByRole('region',{name:'项目成员',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'添加任务',exact:true}).click();const taskEditor=page.getByRole('dialog',{name:'添加任务',exact:true});await expect(taskEditor.getByRole('combobox',{name:'负责人',exact:true})).toHaveValue(s.user.id);await expect(taskEditor.getByLabel('任务描述',{exact:true})).toHaveValue('');await taskEditor.getByRole('button',{name:'取消',exact:true}).click();
 await expect(page.locator('.combined-table thead th').last()).toHaveText('操作');
 await expect(page.getByRole('button',{name:'查看里程碑',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'合并里程碑',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('交付成果');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'合并父任务',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('开始时间');await expect(page.getByRole('dialog')).toContainText('合并里程碑');await page.getByRole('dialog').getByRole('button',{name:'编辑任务',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('任务名称',{exact:true})).toHaveValue('合并父任务');await page.getByRole('dialog').getByRole('button',{name:'选择参与人员',exact:true}).click();await page.getByRole('dialog').getByLabel(s.user.name,{exact:true}).check();await page.getByRole('dialog').getByLabel('过程参与人员',{exact:true}).check();await page.getByRole('dialog').getByRole('button',{name:'完成选择（2人）',exact:true}).click();await page.getByRole('dialog').getByLabel('任务描述',{exact:true}).fill('父任务描述内容');await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.locator('.tree-task').first().locator('td').last().getByRole('button',{name:'编辑任务',exact:true})).toBeVisible();
 const groups=page.locator('.combined-group');await expect(groups).toHaveCount(2);await expect(groups.first()).toContainText('合并子任务');
 await groups.first().getByRole('button',{name:'展开或收起里程碑 合并里程碑'}).click();await expect(groups.first().getByText('合并父任务',{exact:true})).toHaveCount(0);await groups.first().getByRole('button',{name:'展开或收起里程碑 合并里程碑'}).click();
 await page.getByRole('button',{name:'展开或收起任务 合并父任务'}).click();await expect(groups.first().getByText('合并子任务',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'展开或收起任务 合并父任务'}).click();
 await page.getByRole('tab',{name:'项目过程',exact:true}).click();const process=page.getByRole('table',{name:'项目过程列表',exact:true}),rows=process.locator('tbody tr');await expect(rows).toHaveCount(4);await expect(process.locator('thead th')).toHaveText(['时间','里程碑/任务','负责人/参与人员','描述']);await expect(rows.nth(0)).toContainText('合并父任务');await expect(rows.nth(1)).toContainText('合并子任务');await expect(rows.nth(3)).toContainText('合并里程碑');await expect(rows.nth(0)).toContainText('父任务描述内容');await expect(rows.nth(0)).toContainText('过程参与人员');await expect(process).not.toContainText('1.50小时');await expect(process.getByRole('button',{name:'编辑说明'})).toHaveCount(0);
 await page.reload();await expect(rows.nth(0)).toContainText('父任务描述内容');await expect(rows.nth(0)).toContainText('过程参与人员');await page.getByRole('tab',{name:'里程碑与任务',exact:true}).click();await page.getByRole('button',{name:'合并父任务',exact:true}).click();const detail=page.getByRole('dialog');await expect(detail).toContainText('参与人员');await expect(detail).toContainText('父任务描述内容');await expect(detail.locator('dt')).not.toContainText(['执行人']);await detail.getByRole('button',{name:'编辑任务',exact:true}).click();await detail.getByRole('button',{name:'选择参与人员',exact:true}).click();await expect(detail.getByLabel(s.user.name,{exact:true})).toBeChecked();await expect(detail.getByLabel('过程参与人员',{exact:true})).toBeChecked();await detail.getByRole('button',{name:'完成选择（2人）',exact:true}).click();await detail.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('tab',{name:'项目过程',exact:true}).click();
 const tabs=page.getByRole('tablist',{name:'项目详情栏目'}).getByRole('tab');await expect(tabs.last()).toHaveText('备注');
 await page.screenshot({path:'test-results/projects/project-timeline.png',fullPage:true});
})
