import ExcelJS from 'exceljs'
async function excelText(path:string){const book=new ExcelJS.Workbook();await book.xlsx.readFile(path);return JSON.stringify(book.worksheets[0]!.getSheetValues())}
import { test,expect,type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
const password='project-browser-password-123'
async function login(page:Page,account='admin'){await page.goto('/project-system.html');await page.getByLabel('账号',{exact:true}).fill(account);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeAttached()}
async function call(page:Page,path:string,method='GET',data?:unknown){return page.evaluate(async({path,method,data})=>{const s=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()},{path,method,data})}
test('task create and edit milestone dropdown synchronizes both directions and protects stale associations',async({page})=>{
 await login(page);let p=await call(page,'/pm/projects','POST',{title:'任务里程碑选择测试',start:'2026-09-01',end:'2026-12-31'});for(const title of ['选项阶段甲','选项阶段乙'])p=await call(page,`/pm/projects/${p.id}/milestones`,'POST',{title,planned:'2026-10-20'});
 await page.goto(`/project-system.html?project=${p.id}&group=project_tasks`);await page.getByRole('button',{name:'添加任务',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('任务名称',{exact:true}).fill('从任务选择节点');await d.getByLabel('任务里程碑',{exact:true}).click();await d.getByRole('checkbox',{name:/选项阶段甲/}).check();await d.getByRole('checkbox',{name:/选项阶段乙/}).check();await page.screenshot({path:'test-results/projects/task-milestone-picker.png',animations:'disabled'});await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0);
 await page.getByRole('tab',{name:'里程碑与任务',exact:true}).click();const list=page.locator('.combined-list');await expect(list.locator('.combined-group').filter({hasText:'选项阶段甲'})).toContainText('1项任务');await expect(list.locator('.combined-group').filter({hasText:'选项阶段乙'})).toContainText('1项任务');await page.getByRole('tab',{name:'甘特图',exact:true}).click();await expect(page.locator('.pg-task')).toHaveCount(2);
 await page.getByRole('tab',{name:'里程碑与任务',exact:true}).click();const taskRow=page.locator('.tree-task').filter({hasText:'从任务选择节点'}).first();await taskRow.getByRole('button',{name:'编辑任务',exact:true}).click();await d.getByLabel('任务里程碑',{exact:true}).click();await expect(d.getByRole('checkbox',{name:/选项阶段甲/})).toBeChecked();await expect(d.getByRole('checkbox',{name:/选项阶段乙/})).toBeChecked();await d.getByRole('checkbox',{name:/选项阶段甲/}).uncheck();await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0);
 p=await call(page,`/pm/projects/${p.id}`);expect(p.milestones.find((m:{title:string})=>m.title==='选项阶段甲').taskIds).toEqual([]);expect(p.tasks[0].milestoneIds).toEqual([p.milestones.find((m:{title:string})=>m.title==='选项阶段乙').id]);
 // Changes made through the milestone editor must appear in the task editor.
 await page.getByRole('tab',{name:'里程碑与任务',exact:true}).click();await list.locator('.combined-group').filter({hasText:'选项阶段甲'}).getByRole('button',{name:'编辑里程碑',exact:true}).click();await d.getByRole('checkbox',{name:/从任务选择节点/}).check();await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);await page.getByRole('tab',{name:'里程碑与任务',exact:true}).click();await taskRow.getByRole('button',{name:'编辑任务',exact:true}).click();await d.getByLabel('任务里程碑',{exact:true}).click();await expect(d.getByRole('checkbox',{name:/选项阶段甲/})).toBeChecked();await expect(d.getByRole('checkbox',{name:/选项阶段乙/})).toBeChecked();await d.getByRole('button',{name:'清除选择',exact:true}).click();
 p=await call(page,`/pm/projects/${p.id}`);const node=p.milestones.find((m:{title:string})=>m.title==='选项阶段乙');await call(page,`/pm/projects/${p.id}/milestones/${node.id}`,'PUT',{...node,description:'他人同时修改'});await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d.getByRole('alert')).toContainText('刷新');await d.getByRole('button',{name:'取消',exact:true}).click();await page.reload();await taskRow.getByRole('button',{name:'编辑任务',exact:true}).click();await d.getByLabel('任务里程碑',{exact:true}).click();await d.getByRole('button',{name:'清除选择',exact:true}).click();await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0);await page.getByRole('tab',{name:'甘特图',exact:true}).click();await expect(page.locator('tbody[data-milestone-id="unassigned"] .pg-task')).toHaveCount(1);p=await call(page,`/pm/projects/${p.id}`);expect(p.tasks[0].milestoneIds).toEqual([]);expect(p.milestones.every((m:{taskIds:string[]})=>m.taskIds.length===0)).toBe(true)
})
test('milestones support planning, task checks, dependencies, rich views, filters, exports, copy and deletion',async({page})=>{
 await login(page);const s=await call(page,'/session');let p=await call(page,'/pm/projects','POST',{title:'里程碑交互测试'});p=await call(page,`/pm/projects/${p.id}/tasks`,'POST',{title:'验收关联任务',assigneeId:s.user.id,start:'2026-09-01',due:'2026-09-25',state:'进行中',progress:60});let task=p.tasks[0];
 await page.goto(`/project-system.html?view=milestones`);await page.getByLabel('里程碑项目筛选').selectOption(p.id);await page.getByRole('button',{name:'新增里程碑',exact:true}).click();let d=page.getByRole('dialog');await d.getByLabel('里程碑名称',{exact:true}).fill('方案验收节点');await d.getByLabel('计划日期',{exact:true}).fill('2026-09-25');await d.getByLabel('优先级',{exact:true}).selectOption('高');await d.getByLabel('节点说明',{exact:true}).fill('跨部门方案评审');await d.getByLabel('交付成果',{exact:true}).fill('=科研报告');await d.getByLabel('验收标准',{exact:true}).fill('专家签字确认');await d.getByLabel('标签',{exact:true}).fill('科研、重要');await d.getByRole('checkbox',{name:'验收关联任务'}).check();await d.getByLabel('节点状态',{exact:true}).selectOption('进行中');await d.getByLabel('节点进度（%）',{exact:true}).fill('50');await d.getByLabel('执行记录',{exact:true}).fill('已提交初稿');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);
 const table=page.getByRole('table',{name:'里程碑列表',exact:true}),row=table.locator('tbody tr').filter({hasText:'方案验收节点'});await expect(row).toContainText('任务 0/1 · 60%');await expect(row).toContainText('逾期');await row.getByRole('button',{name:'方案验收节点',exact:true}).click();await expect(d).toContainText('专家签字确认');await expect(d).toContainText('已提交初稿');await expect(d).toContainText('验收关联任务');await d.getByRole('button',{name:'编辑里程碑',exact:true}).click();await expect(d.getByRole('button',{name:'关闭',exact:true})).toBeFocused();await d.getByLabel('节点状态',{exact:true}).selectOption('已完成');await d.getByLabel('实际完成日期',{exact:true}).fill('2026-09-25');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d.getByRole('alert')).toContainText('关联任务');await d.getByRole('button',{name:'取消',exact:true}).click();
 task=(await call(page,`/pm/projects/${p.id}`)).tasks[0];p=await call(page,`/pm/projects/${p.id}/tasks/${task.id}`,'PUT',{...task,state:'已完成',progress:100});await page.reload();await row.getByRole('button',{name:'编辑',exact:true}).click();await d.getByLabel('节点状态',{exact:true}).selectOption('已完成');await d.getByLabel('实际完成日期',{exact:true}).fill('2026-09-25');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);await expect(row).toContainText('按期完成');
 await page.getByRole('button',{name:'新增里程碑',exact:true}).click();await d.getByLabel('里程碑名称',{exact:true}).fill('交付上线节点');await d.getByLabel('计划日期',{exact:true}).fill('2026-10-05');const node=(await call(page,`/pm/projects/${p.id}`)).milestones[0];await d.getByLabel('前置里程碑',{exact:true}).selectOption(node.id);await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);
 await page.getByRole('button',{name:'看板',exact:true}).click();await expect(page.locator('.ml-board')).toContainText('方案验收节点');await expect(page.locator('.ml-board')).toContainText('交付上线节点');await page.screenshot({path:'test-results/projects/milestones-board.png',animations:'disabled'});await page.getByRole('button',{name:'时间线',exact:true}).click();await expect(page.locator('.ml-timeline')).toContainText('前置节点：方案验收节点');await page.getByRole('button',{name:'列表',exact:true}).click();
 await row.getByRole('button',{name:'删除',exact:true}).click();await row.getByRole('button',{name:'确认删除',exact:true}).click();await expect(page.getByRole('alert')).toContainText('依赖');await row.getByRole('button',{name:'取消',exact:true}).click();await row.getByRole('button',{name:'复制',exact:true}).click();await expect(d.getByLabel('里程碑名称',{exact:true})).toHaveValue('方案验收节点（副本）');await expect(d.getByLabel('节点状态',{exact:true})).toHaveValue('待开始');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);const copy=table.locator('tbody tr').filter({hasText:'方案验收节点（副本）'});await copy.getByRole('button',{name:'删除',exact:true}).click();await copy.getByRole('button',{name:'确认删除',exact:true}).click();await expect(copy).toHaveCount(0);
 await page.goto('/project-system.html?view=milestones');await page.getByLabel('里程碑项目筛选').selectOption(p.id);await expect(table.locator('tbody tr')).toHaveCount(2);await page.getByLabel('里程碑状态筛选').selectOption('已完成');await expect(table.locator('tbody tr')).toHaveCount(1);await expect(page.getByLabel('里程碑统计')).toContainText(/节点总数\s*1/);const promise=page.waitForEvent('download');await page.getByRole('button',{name:'导出',exact:true}).click();const file=await promise;const csv=await excelText((await file.path())!);expect(csv).toContain("=科研报告");expect(csv).toContain('专家签字确认');expect(csv).not.toContain('交付上线节点');await page.getByLabel('里程碑状态筛选').selectOption('');await page.getByLabel('搜索里程碑').fill('不存在的节点');await expect(table.locator('tbody tr')).toHaveCount(0);await page.getByLabel('搜索里程碑').fill('');await page.screenshot({path:'test-results/projects/milestones-list.png',animations:'disabled'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/projects/milestones-mobile.png',animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'时间线',exact:true}).click();await expect(page.locator('.ml-timeline')).toContainText('交付上线节点');await page.reload();await expect(table).toContainText('交付上线节点')
})
test('assigned milestone owner updates execution only, others read, stale writes require refresh',async({page,browser})=>{
 await login(page);const member=await call(page,'/users','POST',{account:'milestone-browser-owner',name:'里程碑执行教师',role:'导师',password}),other=await call(page,'/users','POST',{account:'milestone-browser-reader',name:'里程碑旁观教师',role:'导师',password});let p=await call(page,'/pm/projects','POST',{title:'节点权限验证',members:[{userId:member.id,role:'项目成员'},{userId:other.id,role:'项目成员'}]});p=await call(page,`/pm/projects/${p.id}/milestones`,'POST',{title:'负责执行节点',planned:'2026-09-30',ownerId:member.id,deliverable:'原定成果',state:'进行中',progress:20});let m=p.milestones[0];
 const context=await browser.newContext();const tab=await context.newPage();try{await login(tab,'milestone-browser-owner');await tab.goto(`/project-system.html?view=milestones`);await tab.getByLabel('里程碑项目筛选').selectOption(p.id);await expect(tab.getByRole('button',{name:'新增里程碑',exact:true})).toHaveCount(0);await tab.getByRole('button',{name:'更新进度',exact:true}).click();let d=tab.getByRole('dialog');await expect(d.getByLabel('里程碑名称',{exact:true})).toBeDisabled();await expect(d.getByLabel('交付成果',{exact:true})).toBeDisabled();await d.getByLabel('节点进度（%）',{exact:true}).fill('75');await d.getByLabel('执行记录',{exact:true}).fill('执行教师更新');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);await expect(tab.getByRole('table')).toContainText('75%');
 await tab.getByRole('button',{name:'更新进度',exact:true}).click();p=await call(page,`/pm/projects/${p.id}`);m=p.milestones[0];await call(page,`/pm/projects/${p.id}/milestones/${m.id}`,'PUT',{...m,progress:80});await d.getByLabel('节点进度（%）',{exact:true}).fill('90');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d.getByRole('alert')).toContainText('刷新');await tab.keyboard.press('Escape');await expect(d).toHaveCount(0);await tab.reload();await expect(tab.getByRole('table')).toContainText('80%');await tab.getByRole('button',{name:'更新进度',exact:true}).click();await d.getByLabel('节点状态',{exact:true}).selectOption('已完成');await d.getByLabel('实际完成日期',{exact:true}).fill('2026-09-30');await d.getByRole('button',{name:'保存里程碑',exact:true}).click();await expect(d).toHaveCount(0);await expect(tab.getByRole('table')).toContainText('按期完成');
 await tab.getByLabel('用户菜单',{exact:true}).click();await tab.getByRole('button',{name:'退出登录',exact:true}).click();await login(tab,'milestone-browser-reader');await tab.goto(`/project-system.html?view=milestones`);await tab.getByLabel('里程碑项目筛选').selectOption(p.id);await expect(tab.getByRole('button',{name:'更新进度',exact:true})).toHaveCount(0);await tab.getByRole('button',{name:'负责执行节点',exact:true}).click();await expect(tab.getByRole('dialog')).toContainText('执行教师更新');await expect(tab.getByRole('dialog').getByRole('button',{name:'更新进度',exact:true})).toHaveCount(0)}finally{await context.close()}
})
