import { test,expect,type Page } from '@playwright/test'
const password='project-browser-password-123'
async function login(page:Page,account='admin'){await page.goto('/project-system.html');await page.getByLabel('账号',{exact:true}).fill(account);await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeAttached()}
async function call(page:Page,path:string,method='GET',data?:unknown){return page.evaluate(async({path,method,data})=>{const s=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()},{path,method,data})}
test('system settings manage project types and dynamic project dropdowns with admin-only access',async({page,browser})=>{
 await login(page);await expect(page.getByRole('button',{name:'系统设置',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'系统管理',exact:true}).click();await expect(page.getByRole('heading',{name:'系统管理',exact:true})).toBeVisible();await page.getByRole('button',{name:'项目类型',exact:true}).click();await page.getByRole('button',{name:'新增项目类型',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('自定义咨询类型');await page.getByLabel('说明',{exact:true}).fill('技术咨询项目');await page.getByRole('button',{name:'保存项目类型',exact:true}).click();const table=page.getByRole('table',{name:'项目类型目录',exact:true});await expect(table).toContainText('自定义咨询类型');await page.getByLabel('搜索项目类型',{exact:true}).fill('查无类型');await expect(table.locator('tbody tr')).toHaveCount(0);await page.getByLabel('搜索项目类型',{exact:true}).fill('');
 await page.goto('/project-system.html?view=projects');await expect(page.getByRole('tab',{name:/自定义咨询类型/})).toBeVisible();await page.getByRole('button',{name:'新建项目',exact:true}).click();let d=page.getByRole('dialog');await d.getByLabel('项目名称',{exact:true}).fill('动态类型关联项目');await d.getByLabel('项目类型',{exact:true}).selectOption('自定义咨询类型');await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toHaveCount(0);
 await page.goto('/project-system.html?view=settings&settings=types');const row=table.locator('tbody tr').filter({hasText:'自定义咨询类型'});await row.getByRole('button',{name:'删除',exact:true}).click();await row.getByRole('button',{name:'确认删除',exact:true}).click();await expect(page.getByRole('alert')).toContainText('正在被项目使用');await row.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('咨询研发类型');await page.getByRole('button',{name:'保存项目类型',exact:true}).click();await expect(table).toContainText('咨询研发类型');await page.reload();await expect(table).toContainText('咨询研发类型');await page.screenshot({path:'test-results/projects/system-config-desktop.png',animations:'disabled'});
 await page.goto('/project-system.html?view=projects');await page.getByRole('tab',{name:/咨询研发类型/}).click();await page.getByRole('button',{name:'动态类型关联项目',exact:true}).click();await expect(page.getByText('咨询研发类型',{exact:true})).toBeVisible();await page.getByRole('button',{name:'编辑项目',exact:true}).click();await expect(d.getByLabel('项目类型',{exact:true})).toHaveValue('咨询研发类型');await d.getByRole('button',{name:'取消',exact:true}).click();await page.goto('/project-system.html?view=milestones');await expect(page.getByLabel('里程碑项目类型').locator('option')).toContainText(['咨询研发类型']);
 await page.goto('/project-system.html?view=settings&settings=types');await page.getByRole('button',{name:'新增项目类型',exact:true}).click();await page.getByLabel('名称',{exact:true}).fill('未使用的可删除类型');await page.getByRole('button',{name:'保存项目类型',exact:true}).click();const unused=table.locator('tbody tr').filter({hasText:'未使用的可删除类型'});await unused.getByRole('button',{name:'删除',exact:true}).click();await unused.getByRole('button',{name:'确认删除',exact:true}).click();await expect(unused).toHaveCount(0);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/projects/system-config-mobile.png',animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await call(page,'/users','POST',{account:'config-teacher',name:'设置普通教师',role:'导师',password});await call(page,'/users','POST',{account:'config-dept',name:'设置系管理员',role:'导师',password});const ctx=await browser.newContext();const other=await ctx.newPage();try{await login(other,'config-teacher');await expect(other.getByRole('button',{name:'系统设置',exact:true})).toHaveCount(0);await other.goto('/project-system.html?view=system-config');await expect(other.getByRole('button',{name:'新增项目类型',exact:true})).toHaveCount(0);await other.getByLabel('用户菜单',{exact:true}).click();await other.getByRole('button',{name:'退出登录',exact:true}).click();await login(other,'config-dept');await expect(other.getByRole('button',{name:'系统设置',exact:true})).toHaveCount(0);await expect(other.getByRole('button',{name:'系统管理',exact:true})).toHaveCount(0);await other.goto('/project-system.html?view=settings&settings=types');await expect(other.getByRole('button',{name:'新增项目类型',exact:true})).toHaveCount(0)}finally{await ctx.close()}
})


test('飞书通知配置、绑定、测试入口和密钥隐藏保持紧凑',async({page})=>{
 await login(page);await page.goto('/project-system.html?view=settings');await page.getByRole('button',{name:'飞书通知',exact:true}).click();
 await expect(page.getByRole('heading',{name:'飞书应用配置',exact:true})).toBeVisible();await page.getByLabel('App ID',{exact:true}).fill('cli_browser123');await page.getByLabel('App Secret',{exact:true}).fill('dummy-browser-secret');await page.getByRole('button',{name:'保存配置',exact:true}).click();await expect(page.getByRole('status')).toContainText('飞书配置已保存');await expect(page.getByLabel('App Secret',{exact:true})).toHaveValue('');await expect(page.getByLabel('App Secret',{exact:true})).toHaveAttribute('placeholder','已保存，留空不修改');
 const data=await call(page,'/feishu');const admin=data.people.find((p:{role:string})=>p.role==='系统管理员');const row=page.getByRole('table',{name:'飞书人员绑定'}).locator('tbody tr').filter({hasText:admin.account});await row.getByRole('combobox').selectOption('email');await row.getByRole('textbox').fill('admin@example.com');await row.getByRole('button',{name:'保存绑定',exact:true}).click();await expect(page.getByRole('status')).toContainText('飞书绑定已保存');await expect(row.getByRole('button',{name:`给${admin.name}发送测试`,exact:true})).toBeEnabled();
 await page.route('**/api/feishu/test',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,error:'',logs:[]})}));await row.getByRole('button',{name:`给${admin.name}发送测试`,exact:true}).click();await expect(page.getByRole('status')).toContainText('请在飞书确认收到');
 await page.getByLabel('启用自动通知',{exact:true}).check();await page.getByRole('button',{name:'保存配置',exact:true}).click();await expect(page.getByRole('status')).toContainText('飞书配置已保存');expect((await call(page,'/feishu')).config.enabled).toBe(true);
 await page.reload();await page.getByRole('button',{name:'飞书通知',exact:true}).click();await expect(page.getByLabel('App Secret',{exact:true})).toHaveValue('');await expect(page.getByLabel('启用自动通知',{exact:true})).toBeChecked();await expect(page.getByRole('table',{name:'飞书人员绑定'})).toContainText(admin.name);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/projects/feishu-settings-mobile.png',animations:'disabled'});
})
