import {test,expect,type Page} from '@playwright/test'
const password='project-browser-password-123'
test('project contacts are selected from the chosen unit and reset when switching units',async({page})=>{
 await page.goto('/');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('navigation',{name:'主导航'})).toBeVisible()
 const a=await call(page,'/organization/units','POST',{name:'联系人单位甲',category:'校内单位'}),b=await call(page,'/organization/units','POST',{name:'联系人单位乙',category:'校外单位'})
 await call(page,'/organization/people','POST',{name:'甲单位联系人',organizationId:a.units.find((unit:{name:string})=>unit.name==='联系人单位甲').id});await call(page,'/organization/people','POST',{name:'乙单位联系人',organizationId:b.units.find((unit:{name:string})=>unit.name==='联系人单位乙').id})
 await page.goto('/project-system.html?view=projects');await page.getByRole('button',{name:'新建项目',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('项目名称',{exact:true}).fill('联系人筛选项目');await d.getByLabel('牵头单位',{exact:true}).selectOption('联系人单位甲');await d.getByRole('button',{name:'添加参与单位',exact:true}).click();const unit=d.getByLabel('单位名称',{exact:true}),contact=d.getByLabel('联系人',{exact:true});await unit.selectOption('联系人单位甲');await expect(contact).toContainText('甲单位联系人');await expect(contact).not.toContainText('乙单位联系人');await contact.selectOption('甲单位联系人');await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toBeHidden()
 await page.getByRole('button',{name:'联系人筛选项目',exact:true}).click();await page.reload();await page.getByRole('button',{name:'编辑项目',exact:true}).click();await expect(contact).toHaveValue('甲单位联系人');await unit.selectOption('联系人单位乙');await expect(contact).toHaveValue('');await expect(contact).not.toContainText('甲单位联系人');await contact.selectOption('乙单位联系人');await d.getByRole('button',{name:'保存',exact:true}).click();await expect(d).toBeHidden();await page.reload();await page.getByRole('button',{name:'编辑项目',exact:true}).click();await expect(contact).toHaveValue('乙单位联系人')
 await d.getByRole('button',{name:'关闭编辑',exact:true}).click();const projectUrl=page.url(),facts=page.locator('.overview-facts')
 for(const [field,name,person] of [['牵头单位','联系人单位甲','甲单位联系人'],['参与单位','联系人单位乙','乙单位联系人']]){
  const link=facts.locator('div').filter({has:page.locator('dt').getByText(field,{exact:true})}).getByRole('link',{name,exact:true});await link.click();await expect(page).toHaveURL(/view=organization/);await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await expect(page.getByRole('table',{name:'人员列表'})).toContainText(person);await page.reload();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await page.goto(projectUrl)
 }
 for(const field of ['负责人','参与人员']){await facts.locator('div').filter({has:page.locator('dt').getByText(field,{exact:true})}).getByRole('link',{name:'系统管理员',exact:true}).click();await expect(page).toHaveURL(/person=/);await expect(page.getByRole('heading',{name:'系统管理员',exact:true})).toBeVisible();await page.goBack();await expect(page.getByRole('heading',{name:'联系人筛选项目',exact:true})).toBeVisible()}
})
async function call(page:Page,path:string,method:string,data:unknown){return page.evaluate(async({path,method,data})=>{const s=await fetch('/api/session').then(r=>r.json());const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrf},body:JSON.stringify(data)});if(!r.ok)throw Error(await r.text());return r.json()},{path,method,data})}
test('campus and external units provide CRUD, personnel profiles, linked accounts, history and mobile navigation',async({page,browser})=>{
 await page.goto('/project-system.html?view=organization');await page.getByLabel('账号',{exact:true}).fill('admin');await page.getByLabel('密码',{exact:true}).fill(password);await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('tablist',{name:'单位分类'}).getByRole('tab')).toHaveCount(2);
 for(const name of ['武汉理工大学','联合研究单位'])await call(page,'/organization/units','POST',{name,category:'校内单位'});
 await page.reload();await page.getByRole('button',{name:'新增单位',exact:true}).click();await page.getByLabel('单位名称',{exact:true}).fill('组织测试学院');await page.getByRole('button',{name:'保存单位',exact:true}).click();const table=page.getByRole('table',{name:'单位列表'});await expect(table).toContainText('组织测试学院');await page.getByLabel('搜索单位名称').fill('查无结果');await expect(table.locator('tbody tr')).toHaveCount(0);await page.getByLabel('搜索单位名称').fill('');
 await table.getByRole('button',{name:'组织测试学院',exact:true}).click();await expect(page).toHaveURL(/unit=/);await page.getByRole('button',{name:'新增人员',exact:true}).click();await page.getByLabel('人员姓名',{exact:true}).fill('组织档案联系人');await page.getByRole('button',{name:'保存人员',exact:true}).click();const members=page.getByRole('table',{name:'人员列表'});await expect(members).toContainText('组织档案联系人');await members.getByRole('button',{name:'组织档案联系人',exact:true}).click();await expect(page.getByRole('heading',{name:'组织档案联系人',exact:true})).toBeVisible();await page.getByRole('button',{name:'编辑人员信息',exact:true}).click();let d=page.getByRole('dialog',{name:'编辑人员信息'});await d.getByLabel('研究方向',{exact:true}).fill('校企协同研发');await d.getByRole('button',{name:'保存人员信息',exact:true}).click();await expect(d).toBeHidden();await expect(page.getByRole('region',{name:'人员基本信息'})).toContainText('校企协同研发');
 const chosen=page.waitForEvent('filechooser');await page.getByRole('button',{name:'上传附件',exact:true}).click();await (await chosen).setFiles({name:'组织履历.txt',mimeType:'text/plain',buffer:Buffer.from('organization profile')});await expect(page.getByText('附件已上传并保存',{exact:true})).toBeVisible();await page.reload();await expect(page.locator('.side-file')).toContainText('组织履历.txt');await page.getByRole('button',{name:'返回人员信息',exact:true}).click();await expect(members).toContainText('组织档案联系人');
 const teacher=await call(page,'/users','POST',{account:'org-linked',name:'组织关联教师',role:'导师',password});await page.getByRole('button',{name:'新增人员',exact:true}).click();await page.getByLabel('关联已有账号（选填）').selectOption(teacher.id);await page.getByRole('button',{name:'保存人员',exact:true}).click();await expect(members).toContainText('组织关联教师');await page.getByRole('button',{name:/返回校内单位列表/}).click();
 const row=table.locator('tbody tr').filter({hasText:'组织测试学院'});await row.getByRole('button',{name:'删除',exact:true}).click();await row.getByRole('button',{name:'确认删除',exact:true}).click();await expect(page.getByRole('alert')).toContainText('还有人员');await row.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('单位名称',{exact:true}).fill('组织测试企业');await page.getByRole('combobox',{name:/^单位分类/}).selectOption('校外单位');await page.getByRole('button',{name:'保存单位',exact:true}).click();await expect(row).toHaveCount(0);await page.getByRole('tab',{name:'校外单位',exact:true}).click();await table.getByRole('button',{name:'组织测试企业',exact:true}).click();await expect(members).toContainText('组织关联教师');await page.reload();await expect(members).toContainText('组织档案联系人');
 let personRow=members.locator('tbody tr').filter({hasText:'组织档案联系人'});await personRow.getByRole('button',{name:'编辑',exact:true}).click();await page.getByLabel('人员姓名',{exact:true}).fill('改名档案联系人');await page.getByRole('button',{name:'保存人员',exact:true}).click();personRow=members.locator('tbody tr').filter({hasText:'改名档案联系人'});await personRow.getByRole('button',{name:'删除',exact:true}).click();await personRow.getByRole('button',{name:'确认删除',exact:true}).click();await expect(personRow).toHaveCount(0);
 const linkedRow=members.locator('tbody tr').filter({hasText:'组织关联教师'});await linkedRow.getByRole('button',{name:'移出单位',exact:true}).click();await linkedRow.getByRole('button',{name:'确认移出',exact:true}).click();await expect(linkedRow).toHaveCount(0);await page.getByRole('button',{name:/返回校外单位列表/}).click();const empty=table.locator('tbody tr').filter({hasText:'组织测试企业'});await empty.getByRole('button',{name:'删除',exact:true}).click();await empty.getByRole('button',{name:'确认删除',exact:true}).click();await expect(empty).toHaveCount(0);
 await page.setViewportSize({width:390,height:844});await expect(page.getByRole('tab',{name:'校外单位',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const ctx=await browser.newContext(),other=await ctx.newPage();try{await other.goto('/project-system.html?view=organization');await other.getByLabel('账号',{exact:true}).fill('org-linked');await other.getByLabel('密码',{exact:true}).fill(password);await other.getByRole('button',{name:'登录',exact:true}).click();await expect(other.getByRole('tab',{name:'校内单位',exact:true})).toBeVisible();await expect(other.getByRole('button',{name:'新增单位',exact:true})).toHaveCount(0)}finally{await ctx.close()}
})
