<script setup lang="ts">
import {computed,onMounted,ref} from 'vue'
import {account,api} from './api'
import type {LiveProject,ProjectPerson} from './project-api'
import {nextDates,personTaskLoad,type Capacity} from './task-load'
const props=defineProps<{projects:LiveProject[];people:ProjectPerson[]}>()
const emit=defineEmits<{'open-project':[id:string]}>()
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date())
const start=ref(today),query=ref(''),filter=ref('全部'),capacities=ref<Capacity[]>([]),error=ref(''),loading=ref(true),busy=ref(false)
const selected=ref(''),selectedDate=ref(''),editing=ref<ProjectPerson>(),draft=ref(5),editRevision=ref(0)
const dates=computed(()=>nextDates(start.value||today))
const rows=computed(()=>props.people.filter(p=>p.active&&p.role!=='只读访客').map(person=>personTaskLoad(person,props.projects,dates.value,today,capacities.value.find(c=>c.userId===person.id)?.dailyLimit)))
const visible=computed(()=>rows.value.filter(r=>(!query.value||r.person.name.includes(query.value))&&(filter.value==='全部'||(filter.value==='超负荷'?r.days.some(d=>d.percent!==null&&d.percent>100):filter.value==='未设置上限'?r.limit===undefined:r.pending.length===0))).sort((a,b)=>(b.days[0]!.percent??-1)-(a.days[0]!.percent??-1)||b.pending.length-a.pending.length||a.person.name.localeCompare(b.person.name,'zh-CN')))
const stats=computed(()=>({people:rows.value.length,over:rows.value.filter(r=>r.days.some(d=>d.percent!==null&&d.percent>100)).length,unset:rows.value.filter(r=>r.limit===undefined).length,tasks:props.projects.reduce((n,p)=>n+p.tasks.filter(t=>t.state!=='已完成').length,0)}))
const detail=computed(()=>rows.value.find(r=>r.person.id===selected.value))
const detailTasks=computed(()=>detail.value?.tasks.filter(t=>!selectedDate.value||(t.state!=='已完成'&&(t.start||t.due)<=selectedDate.value&&(t.due||t.start)>=selectedDate.value&&(t.start||t.due))).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'))||[])
function editable(p:ProjectPerson){return account.value?.role==='系统管理员'||account.value?.id===p.id}
function edit(p:ProjectPerson){const config=capacities.value.find(c=>c.userId===p.id);editing.value=p;draft.value=config?.dailyLimit||5;editRevision.value=config?.revision||0;error.value=''}
async function load(){loading.value=true;error.value='';try{capacities.value=await api<Capacity[]>('/pm/task-capacity')}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
async function save(){busy.value=true;error.value='';try{capacities.value=await api<Capacity[]>('/pm/task-capacity/'+editing.value!.id,'PUT',{dailyLimit:draft.value,revision:editRevision.value});editing.value=undefined}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function tone(percent:number|null,count:number){return percent===null?'unknown':percent>100?'over':percent>=80?'busy':count?'available':'idle'}
function select(id:string,date=''){selected.value=id;selectedDate.value=date}
onMounted(load)
</script>
<template>
 <section class="panel task-load-overview" aria-label="人员任务饱和度">
  <div class="load-header"><h2>人员任务饱和度</h2><div class="load-controls"><input v-model="query" type="search" placeholder="搜索人员" aria-label="搜索人员"><input v-model="start" type="date" aria-label="饱和度起始日期"><select v-model="filter" aria-label="饱和度筛选"><option v-for="f in ['全部','超负荷','未设置上限','暂无任务']" :key="f">{{ f }}</option></select><button :disabled="loading||busy" @click="load">刷新</button></div></div>
  <div class="load-summary"><span>人员 <b>{{ stats.people }}</b></span><span>未完成任务 <b>{{ stats.tasks }}</b></span><span>超负荷人员 <b>{{ stats.over }}</b></span><span>未设置上限 <b>{{ stats.unset }}</b></span><details><summary>统计口径</summary><p>按任务开始至截止日期逐日计数，负责人和参与人员均计入，每人每项任务计一次；已完成任务不占额度。未填写任何日期的任务单独计数。饱和度＝当日任务数÷每日上限。仅统计当前账号可见的项目，按每日任务数量计算。</p></details></div>
  <p v-if="error&&!editing" role="alert" class="pm-error">{{ error }} <button @click="load">重试</button></p><p v-if="loading" role="status">正在加载…</p>
  <div v-else-if="!error" class="load-scroll"><table class="load-table" aria-label="人员饱和度列表"><thead><tr><th>人员</th><th>未完成</th><th>已完成</th><th>逾期</th><th>无日期</th><th :title="dates[0]">当日任务</th><th>每日上限</th><th :title="dates[0]">饱和度</th><th><div class="load-days"><span v-for="d in dates" :key="d" :title="d">{{ d.slice(8) }}日</span></div></th></tr></thead><tbody><tr v-for="r in visible" :key="r.person.id"><td><button class="load-person" @click="select(r.person.id)">{{ r.person.name }}</button></td><td>{{ r.pending.length }}</td><td>{{ r.done }}</td><td :class="{'load-alert':r.overdue}">{{ r.overdue }}</td><td>{{ r.undated }}</td><td>{{ r.days[0]!.count }}</td><td><button v-if="editable(r.person)" class="load-limit" :aria-label="`设置${r.person.name}每日任务上限`" @click="edit(r.person)">{{ r.limit??'设置' }}</button><span v-else>{{ r.limit??'未设置' }}</span></td><td><span :class="{'load-alert':(r.days[0]!.percent||0)>100}">{{ r.days[0]!.percent===null?'未设置':r.days[0]!.percent+'%' }}</span></td><td><div class="load-days"><button v-for="d in r.days" :key="d.date" :class="tone(d.percent,d.count)" :title="`${r.person.name} · ${d.date} · ${d.count}项任务 · ${d.percent===null?'未设置上限':d.percent+'%'}`" :aria-label="`${r.person.name} ${d.date} ${d.count}项任务`" @click="select(r.person.id,d.date)">{{ d.count }}</button></div></td></tr><tr v-if="!visible.length"><td colspan="9" class="load-empty">暂无符合条件的人员</td></tr></tbody></table></div>
  <div class="load-footer"><span>{{ dates[0] }} — {{ dates[13] }}</span><span v-for="[cls,label] in [['idle','无任务'],['available','可承接'],['busy','接近上限'],['over','超负荷'],['unknown','未设置上限']]" :key="cls"><i :class="cls"></i>{{ label }}</span></div>
 </section>
 <section v-if="detail" class="panel load-detail"><div class="load-header"><h2>{{ detail.person.name }}的任务{{ selectedDate?' · '+selectedDate:'' }}</h2><button @click="selected=''">关闭</button></div><div class="load-scroll"><table class="load-detail-table" aria-label="人员任务明细"><thead><tr><th>所属项目</th><th>任务名称</th><th>任务类型</th><th>参与身份</th><th>状态</th><th>进度</th><th>截止日期</th></tr></thead><tbody><tr v-for="t in detailTasks" :key="t.id"><td><button class="load-person" @click="emit('open-project',t.project.id)">{{ t.project.title }}</button></td><td><button class="load-task" @click="emit('open-project',t.project.id)">{{ t.title }}</button></td><td>{{ t.taskType||'未选择' }}</td><td>{{ t.assigneeId===detail.person.id?'负责人':'参与人员' }}</td><td>{{ t.state }}</td><td>{{ t.progress }}%</td><td>{{ t.due||'未填写' }}</td></tr><tr v-if="!detailTasks.length"><td colspan="7" class="load-empty">暂无任务</td></tr></tbody></table></div></section>
 <div v-if="editing" class="pm-modal"><form class="pm-form load-form" role="dialog" aria-modal="true" aria-labelledby="capacity-heading" @submit.prevent="save"><div class="pm-form-header"><h2 id="capacity-heading">{{ editing.name }} · 每日任务上限</h2><button type="button" :disabled="busy" @click="editing=undefined">关闭</button></div><label>每日最多任务数<input v-model.number="draft" type="number" min="1" max="1000" step="1" required></label><p v-if="error" role="alert" class="pm-error">{{ error }}</p><div class="pm-form-actions"><button type="button" :disabled="busy" @click="editing=undefined">取消</button><button class="pm-primary" :disabled="busy">{{ busy?'保存中…':'保存' }}</button></div></form></div>
</template>
<style scoped>
.task-load-overview,.load-detail{font-size:14px;margin-bottom:0}.load-header{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:10px}.load-header h2{font-size:14px;color:var(--accent)}.load-controls{display:flex;align-items:center;flex-wrap:wrap;gap:6px}.load-controls input,.load-controls select,.load-header>button,.load-controls button{font:inherit;border:1px solid var(--line);border-radius:5px;background:#fff;padding:5px 7px;color:inherit}.load-controls input[type=search]{width:150px}.load-summary{display:flex;align-items:center;flex-wrap:wrap;gap:15px;margin-bottom:10px;color:var(--muted)}.load-summary b{color:var(--project-blue)}.load-summary details{position:relative;margin-left:auto}.load-summary summary{cursor:pointer}.load-summary details p{position:absolute;right:0;top:25px;width:300px;background:#fff;border:1px solid var(--line);padding:10px;z-index:2;border-radius:5px}.load-scroll{overflow-x:auto}.load-table,.load-detail-table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}.load-table{min-width:1050px}.load-table th,.load-table td,.load-detail-table th,.load-detail-table td{border-bottom:1px solid var(--line);padding:7px 8px;vertical-align:middle}.load-table th,.load-detail-table th{background:#f6f5f3;white-space:nowrap;font-weight:700}.load-table th:first-child{min-width:95px}.load-table th:last-child{width:460px}.load-days{display:grid;grid-template-columns:repeat(14,minmax(25px,1fr));gap:3px;min-width:430px;text-align:center}.load-days>span{font-size:12px;font-weight:400;color:var(--muted)}.load-days button{border:0;border-radius:4px;min-height:25px;font:inherit;color:#473e36;padding:2px;cursor:pointer}.load-days button:hover{outline:1px solid var(--accent)}.idle{background:#eeeae6}.available{background:#e4f1e8}.busy{background:#f6e5cd}.over{background:#f2d4ca}.unknown{background:#f6f5f3}.load-days .over,.load-alert{color:var(--accent);font-weight:600}.load-person,.load-task,.load-limit{padding:0;border:0;background:transparent;font:inherit;cursor:pointer;text-align:left}.load-person{color:var(--project-blue)}.load-task,.load-limit{color:var(--accent)}.load-person:hover,.load-task:hover,.load-limit:hover{text-decoration:underline}.load-footer{display:flex;align-items:center;flex-wrap:wrap;gap:12px;color:var(--muted);font-size:12px;margin-top:8px}.load-footer span{display:inline-flex;align-items:center;gap:4px}.load-footer i{width:12px;height:12px;border-radius:3px}.load-empty{text-align:center;color:var(--muted)}.load-detail-table{min-width:800px}.load-form{width:min(450px,95vw)}@media(max-width:720px){.load-summary{gap:8px}.load-controls input[type=search]{width:130px}.load-summary details p{width:260px}.load-header{align-items:flex-start}}
</style>
