<script setup lang="ts">
import { computed } from 'vue'
import {
  ArrowLeft, ArrowRight, CalendarDays, Check, CircleAlert,
  FileCheck2, FileText, FolderOpen, MessageSquareText, Pin,
  UsersRound,
} from '@lucide/vue'
import { detailTabs, projectDetail, type DetailGroup, type ProjectCore } from './project-detail-data'

const props = defineProps<{ project: ProjectCore; group: DetailGroup }>()
const emit = defineEmits<{ back: []; changeGroup: [group: DetailGroup] }>()
const detail = computed(() => projectDetail(props.project))
const completeTasks = computed(() => detail.value.tasks.filter(task => task.state === '已完成').length)
const totalHours = computed(() => detail.value.timesheets.reduce((total, entry) => total + entry.hours, 0))
const activeTab = computed(() => detailTabs.find(tab => tab.id === props.group)?.label || '概览')
const ganttBars = computed(() => detail.value.tasks.map((task, index) => ({
  ...task,
  left: `${[2, 23, 44, 65, 78][index]}%`,
  width: `${[20, 22, 25, 15, 20][index]}%`,
})))
function tab(group: DetailGroup) { emit('changeGroup', group) }
</script>

<template>
  <div class="detail-page">
    <button class="detail-back" @click="emit('back')"><ArrowLeft :size="16" />返回项目台账</button>
    <section class="detail-hero">
      <div class="detail-hero-main"><div class="detail-ident"><span class="detail-type">{{ project.type }}</span><span class="project-code">{{ project.code }}</span><span class="status" :class="project.status === '正常推进' ? 'good' : 'warn'">{{ project.status }}</span></div><h1>{{ project.title }}</h1><p>{{ detail.goal }}</p><div class="detail-hero-meta"><span><UsersRound :size="15" />负责人 {{ project.owner }}</span><span><CalendarDays :size="15" />{{ detail.start }} 至 {{ detail.end }}</span><span><FolderOpen :size="15" />{{ project.phase }}</span></div></div>
      <div class="detail-progress"><span>整体进度</span><strong>{{ project.progress }}<small>%</small></strong><div class="progress-track"><span :style="{ width: `${project.progress}%` }"></span></div><small>最近节点：{{ project.due }}</small></div>
    </section>

    <div class="detail-tabs" role="tablist" aria-label="项目详情栏目"><button v-for="item in detailTabs" :key="item.id" role="tab" :aria-selected="group === item.id" :aria-controls="'detail-content'" :class="{ selected: group === item.id }" @click="tab(item.id)">{{ item.label }}</button></div>
    <p class="detail-tab-hint">左右滑动查看更多栏目</p>
    <div id="detail-content" role="tabpanel" :aria-label="activeTab" tabindex="-1">
      <template v-if="group === 'project_overview'">
        <div class="overview-metrics"><div><span>任务进度</span><strong>{{ completeTasks }}/{{ detail.tasks.length }}</strong><small>已完成 / 总任务</small></div><div><span>累计示例工时</span><strong>{{ totalHours }}<small>小时</small></strong><small>{{ detail.team.length }} 位参与人员</small></div><div><span>里程碑</span><strong>2/5</strong><small>下个节点 {{ project.due }}</small></div><div><span>开放风险</span><strong>{{ detail.risks.length }}</strong><small>需按例会跟踪</small></div></div>
        <div class="overview-grid"><section class="panel"><div class="panel-head"><div><h2>项目基本信息</h2><p>立项与执行信息</p></div></div><dl class="overview-facts"><div><dt>项目编号</dt><dd>{{ project.code || '未填写' }}</dd></div><div><dt>项目类型</dt><dd>{{ project.type }}</dd></div><div><dt>牵头单位</dt><dd>{{ project.unit }}</dd></div><div><dt>项目来源</dt><dd>{{ detail.sponsor }}</dd></div><div><dt>项目负责人</dt><dd>{{ project.owner }}</dd></div><div><dt>计划周期</dt><dd>{{ detail.start }} — {{ detail.end }}</dd></div><div class="wide"><dt>项目简介</dt><dd>{{ detail.goal }}</dd></div></dl></section>
          <section class="panel overview-next"><div class="panel-head"><h2>当前阶段</h2><span class="status" :class="project.status === '正常推进' ? 'good' : 'warn'">{{ project.status }}</span></div><div class="current-phase"><small>正在执行</small><strong>{{ project.phase }}</strong><p>{{ project.summary }}</p></div><div class="overview-next-row"><span>下一个关键节点</span><strong>{{ detail.milestones[3]!.title }}</strong><small>{{ detail.milestones[3]!.planned }}</small></div><button class="text-link" @click="tab('project_milestones')">查看完整里程碑<ArrowRight :size="16" /></button></section></div>
        <div class="overview-grid"><section class="panel"><div class="panel-head"><h2>近期任务</h2><button class="text-link" @click="tab('project_tasks')">任务<ArrowRight :size="16" /></button></div><div v-for="task in detail.tasks.slice(2, 5)" :key="task.id" class="compact-row"><span class="task-dot" :class="task.state === '进行中' ? 'current' : ''"></span><div><strong>{{ task.title }}</strong><small>{{ task.owner }} · 截止 {{ task.due }}</small></div><span class="status" :class="task.state === '进行中' ? 'warn' : 'good'">{{ task.state }}</span></div></section>
          <section class="panel"><div class="panel-head"><h2>最近项目记录</h2><button class="text-link" @click="tab('project_activity')">全部记录<ArrowRight :size="16" /></button></div><div v-for="entry in detail.activities.slice(0, 3)" :key="entry.action" class="compact-row"><span class="activity-dot"></span><div><strong>{{ entry.person }} · {{ entry.action }}</strong><small>{{ entry.detail }}</small></div><time>{{ entry.date }}</time></div></section></div>
      </template>

      <section v-else-if="group === 'project_tasks'" class="panel detail-section"><div class="panel-head"><div><h2>任务</h2><p>任务层级、负责人、进度和前置任务</p></div><span class="section-count">{{ completeTasks }} / {{ detail.tasks.length }} 已完成</span></div><div class="table-wrap"><table class="detail-table"><thead><tr><th>任务</th><th>负责人</th><th>前置任务</th><th>截止日期</th><th>进度</th><th>状态</th></tr></thead><tbody><tr v-for="task in detail.tasks" :key="task.id"><td><span class="task-name" :class="{ child: task.parentId }"><small>{{ task.id.split('-').at(-1) }}</small><strong>{{ task.title }}</strong></span></td><td>{{ task.owner }}</td><td>{{ task.dependsOn }}</td><td>{{ task.due }}</td><td><div class="table-progress"><span class="progress-track"><span :style="{ width: `${task.progress}%` }"></span></span>{{ task.progress }}%</div></td><td><span class="status" :class="task.state === '已完成' ? 'good' : 'warn'">{{ task.state }}</span></td></tr></tbody></table></div><p class="section-footnote">缩进的子任务归属上一条主任务；正式版本将支持任务依赖校验、分工与更新。</p></section>

      <template v-else-if="group === 'project_timesheets'"><div class="mini-metrics"><div><span>本周填报</span><strong>{{ totalHours }} 小时</strong></div><div><span>已确认</span><strong>{{ totalHours - 5.5 }} 小时</strong></div><div><span>待确认</span><strong>5.5 小时</strong></div></div><section class="panel detail-section"><div class="panel-head"><div><h2>工时表</h2><p>按任务记录投入时间，供项目负责人核对</p></div><span class="section-count">2026年9月</span></div><div class="table-wrap"><table class="detail-table"><thead><tr><th>日期</th><th>填报人</th><th>关联任务</th><th>工时</th><th>状态</th></tr></thead><tbody><tr v-for="entry in detail.timesheets" :key="entry.date + entry.person"><td>{{ entry.date }}</td><td>{{ entry.person }}</td><td>{{ entry.task }}</td><td><strong>{{ entry.hours }} 小时</strong></td><td><span class="status" :class="entry.state === '已确认' ? 'good' : 'warn'">{{ entry.state }}</span></td></tr></tbody></table></div></section></template>

      <template v-else-if="group === 'project_participants'"><section class="panel detail-section"><div class="panel-head"><div><h2>参与单位</h2><p>明确牵头、协作与执行职责</p></div><span class="section-count">{{ detail.units.length }} 家单位 / 团队</span></div><div class="unit-grid"><article v-for="unit in detail.units" :key="unit.name" class="unit-card"><span class="unit-role">{{ unit.role }}</span><h3>{{ unit.name }}</h3><p>{{ unit.duty }}</p><small>联系人：{{ unit.contact }}</small></article></div></section><section class="panel detail-section"><div class="panel-head"><h2>项目人员</h2><span class="section-count">{{ detail.team.length }} 人</span></div><div class="people-list"><div v-for="(person, index) in detail.team" :key="person"><span class="person-avatar">{{ person.slice(0, 1) }}</span><strong>{{ person }}</strong><span>{{ ['项目负责人', '项目协调人', '任务成员'][index] }}</span><small>{{ index === 0 ? '进度统筹、成果确认' : index === 1 ? '跨单位协作、过程资料' : '专题任务、数据和文件' }}</small></div></div></section></template>

      <section v-else-if="group === 'project_milestones'" class="panel detail-section"><div class="panel-head"><div><h2>里程碑计划</h2><p>计划时间、实际完成和交付物并列查看</p></div><span class="section-count">2 / 5 已完成</span></div><div class="milestone-list"><div v-for="(milestone, index) in detail.milestones" :key="milestone.title" class="milestone-row"><span class="milestone-marker" :class="milestone.state === '已完成' ? 'done' : milestone.state === '进行中' ? 'current' : ''"><Check v-if="milestone.state === '已完成'" :size="15" />{{ milestone.state !== '已完成' ? String(index + 1).padStart(2, '0') : '' }}</span><div class="milestone-main"><strong>{{ milestone.title }}</strong><small>交付物：{{ milestone.deliverable }}</small></div><div class="milestone-date"><span>计划 {{ milestone.planned }}</span><small>实际 {{ milestone.actual }}</small></div><span class="status" :class="milestone.state === '已完成' ? 'good' : 'warn'">{{ milestone.state }}</span></div></div></section>

      <section v-else-if="group === 'project_files'" class="panel detail-section"><div class="panel-head"><div><h2>项目文件</h2><p>项目文件、技术资料、过程记录和阶段成果</p></div><span class="section-count">{{ detail.files.length }} 个文件</span></div><div class="file-categories"><span v-for="category in ['项目文件', '技术资料', '过程记录', '阶段成果']" :key="category"><FolderOpen :size="17" />{{ category }}</span></div><div class="table-wrap"><table class="detail-table"><thead><tr><th>文件名称</th><th>分类</th><th>版本</th><th>上传人</th><th>更新时间</th></tr></thead><tbody><tr v-for="file in detail.files" :key="file.name"><td><span class="file-name"><FileText :size="18" />{{ file.name }}</span></td><td>{{ file.category }}</td><td>{{ file.version }}</td><td>{{ file.owner }}</td><td>{{ file.updated }}</td></tr></tbody></table></div><p class="section-footnote">文件为示例名称；正式版本将接入上传、权限和版本留痕。</p></section>

      <section v-else-if="group === 'project_discussions'" class="detail-section"><div class="panel-head"><div><h2>讨论区</h2><p>项目协作问题按主题集中讨论</p></div><span class="section-count">{{ detail.discussions.length }} 个主题</span></div><article v-for="thread in detail.discussions" :key="thread.title" class="panel discussion-card"><div class="discussion-avatar">{{ thread.author.slice(0, 1) }}</div><div><div class="discussion-head"><h3>{{ thread.title }}</h3><span>{{ thread.date }}</span></div><small>{{ thread.author }} 发起</small><p>{{ thread.body }}</p><span class="discussion-replies"><MessageSquareText :size="15" />{{ thread.replies }} 条回复</span></div></article></section>

      <section v-else-if="group === 'project_gantt'" class="panel detail-section"><div class="panel-head"><div><h2>项目甘特图</h2><p>任务排期与先后关系的示意视图</p></div><span class="section-count">{{ detail.start }} — {{ detail.end }}</span></div><div class="gantt-scroll"><div class="gantt"><div class="gantt-header"><span>任务 / 负责人</span><div><span>启动</span><span>方案</span><span>实施</span><span>检查</span><span>验收</span></div></div><div v-for="(task, index) in ganttBars" :key="task.id" class="gantt-row"><span><strong>{{ task.title }}</strong><small>{{ task.owner }} · {{ task.due }}</small></span><div class="gantt-grid"><i class="gantt-bar" :class="index < 2 ? 'done' : index === 2 ? 'current' : ''" :style="{ left: task.left, width: task.width }"></i></div></div></div></div><p class="section-footnote">横轴按阶段展示示例排期；正式版本将根据任务起止日期与依赖关系计算。</p></section>

      <section v-else-if="group === 'project_notes'" class="detail-section"><div class="panel-head"><div><h2>项目备注</h2><p>保留会议提醒和执行约定</p></div><span class="section-count">{{ detail.notes.length }} 条备注</span></div><div class="note-grid"><article v-for="note in detail.notes" :key="note.title" class="panel note-card"><div class="note-top"><span v-if="note.pinned"><Pin :size="14" />置顶</span><small>{{ note.date }}</small></div><h3>{{ note.title }}</h3><p>{{ note.body }}</p><small>{{ note.author }} 记录</small></article></div></section>

      <section v-else-if="group === 'project_activity'" class="panel detail-section"><div class="panel-head"><div><h2>项目记录</h2><p>任务、阶段、文件和风险的变更留痕</p></div><span class="section-count">最近 {{ detail.activities.length }} 条</span></div><div class="activity-list"><div v-for="entry in detail.activities" :key="entry.action" class="activity-entry"><span class="activity-node"></span><div><strong>{{ entry.person }} {{ entry.action }}</strong><p>{{ entry.detail }}</p><span class="activity-kind">{{ entry.kind }}</span></div><time>{{ entry.date }}</time></div></div></section>

      <section v-else-if="group === 'project_risks'" class="panel detail-section"><div class="panel-head"><div><h2>风险与问题</h2><p>问题归属、优先级与应对措施</p></div><span class="section-count">{{ detail.risks.length }} 项开放</span></div><article v-for="risk in detail.risks" :key="risk.title" class="risk-detail-row"><span class="risk-level" :class="risk.level === '高' ? 'high' : 'medium'">{{ risk.level }}</span><div><h3>{{ risk.title }}</h3><p>{{ risk.response }}</p><small>责任人 {{ risk.owner }}</small></div><span class="status warn">{{ risk.state }}</span></article></section>

      <section v-else class="panel detail-section"><div class="panel-head"><div><h2>审批与变更</h2><p>记录需要确认的计划、技术和范围调整</p></div><span class="section-count">{{ detail.approvals.length }} 项</span></div><article v-for="approval in detail.approvals" :key="approval.title" class="approval-row"><span class="row-icon"><FileCheck2 :size="20" /></span><div><h3>{{ approval.title }}</h3><p>{{ approval.detail }}</p><small>{{ approval.applicant }} · {{ approval.submitted }} 提交</small></div><span class="status" :class="approval.state === '已通过' ? 'good' : 'warn'">{{ approval.state }}</span></article></section>
    </div>
    <div class="detail-tail"><CircleAlert :size="15" />以上为静态示例，表格、文件与讨论不会写入数据。</div>
  </div>
</template>
