<script setup lang="ts">
import ProjectTaskCheckbox from './ProjectTaskCheckbox.vue'
import { ref } from 'vue'
import { ArrowRight } from '@lucide/vue'
import type { ProjectCore, ProjectDetailData } from './project-detail-data'
defineProps<{groups:{project:ProjectCore;tasks:ProjectDetailData['tasks']}[];label:string;empty:string}>()
const emit=defineEmits<{'open-project':[id:string]}>()
const collapsed=ref<string[]>([])
const closedTasks=ref<string[]>([])
function toggleTask(id:string){closedTasks.value=closedTasks.value.includes(id)?closedTasks.value.filter(value=>value!==id):[...closedTasks.value,id]}
function visibleTasks(tasks:ProjectDetailData['tasks']){const byId=new Map(tasks.map(task=>[task.id,task]));return tasks.filter(task=>{let parent=task.parentId;const seen=new Set<string>();while(parent&&byId.has(parent)&&!seen.has(parent)){if(closedTasks.value.includes(parent))return false;seen.add(parent);parent=byId.get(parent)!.parentId}return true})}
function toggle(id:string){collapsed.value=collapsed.value.includes(id)?collapsed.value.filter(value=>value!==id):[...collapsed.value,id]}
function dueSoon(date:string){const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const days=(Date.parse(date)-Date.parse(today))/86400000;return days>=0&&days<=3}
</script>
<template>
 <div class="wb-table-scroll"><table class="wb-table wb-fold-table" :aria-label="label"><colgroup><col><col class="wf-type"><col class="wf-owner"><col class="wf-state"><col class="wf-progress"><col class="wf-due"><col class="wf-action"></colgroup><thead><tr><th>项目/任务名称</th><th>任务类型</th><th>负责人</th><th>状态</th><th>任务进度</th><th>截止日期</th><th>操作</th></tr></thead>
 <tbody v-for="group in groups" :key="group.project.id"><tr class="wf-project-row"><td><div class="wf-name"><button class="text-link wf-toggle" :aria-label="`展开或收起项目 ${group.project.title}`" :aria-expanded="!collapsed.includes(group.project.id)" @click="toggle(group.project.id)"><span aria-hidden="true">{{ collapsed.includes(group.project.id)?'▸':'▾' }}</span></button><button class="text-link wf-project-name" @click="emit('open-project',group.project.id)">{{ group.project.title }}</button><span class="wf-count">（{{ group.tasks.length }}项任务）</span></div></td><td>—</td><td>{{ group.project.owner }}</td><td>—</td><td>—</td><td>{{ group.project.due||'未填写' }}</td><td><button class="text-link" @click="emit('open-project',group.project.id)">进入项目<ArrowRight :size="15" /></button></td></tr>
 <template v-if="!collapsed.includes(group.project.id)"><tr v-for="task in visibleTasks(group.tasks)" :key="task.id" class="wf-task-row"><td><div class="wf-name wf-task-name" :class="{'wf-subtask':task.parentId}"><button v-if="group.tasks.some(child=>child.parentId===task.id)" class="text-link wf-toggle" :aria-label="`展开或收起任务 ${task.title}`" :aria-expanded="!closedTasks.includes(task.id)" @click="toggleTask(task.id)"><span aria-hidden="true">{{ closedTasks.includes(task.id)?'▸':'▾' }}</span></button><span v-else class="wf-spacer"></span><ProjectTaskCheckbox :task-id="task.id" :title="task.title" :state="task.state" /><button class="text-link wf-task-link" :class="{'task-completed':task.state==='已完成'}" @click="emit('open-project',group.project.id)"><span v-if="task.parentId">↳ </span>{{ task.title }}</button></div></td><td>{{ task.taskType||'未选择' }}</td><td>{{ task.owner||'—' }}</td><td><span class="wb-state" :class="{done:task.state==='已完成',running:task.state==='进行中'}">{{ task.state }}</span></td><td><div class="wb-progress"><span class="progress-track" role="progressbar" :aria-label="`${task.title}进度`" :aria-valuenow="task.progress" aria-valuemin="0" aria-valuemax="100"><span :style="{width:`${task.progress}%`}"></span></span><span>{{ task.progress }}%</span></div></td><td :class="{'wf-due-soon':dueSoon(task.due)}">{{ task.due||'未填写' }}</td><td><button class="text-link" @click="emit('open-project',group.project.id)">查看任务<ArrowRight :size="15" /></button></td></tr><tr v-if="!group.tasks.length"><td colspan="7" class="wb-empty">本项目暂无任务</td></tr></template></tbody>
 <tbody v-if="!groups.length"><tr><td colspan="7" class="wb-empty">{{ empty }}</td></tr></tbody></table></div>
</template>
<style scoped>
.wb-fold-table{table-layout:fixed;min-width:880px}.wf-type{width:90px}.wf-owner{width:120px}.wf-state{width:90px}.wf-progress{width:160px}.wf-due{width:115px}.wf-action{width:110px}.wb-fold-table td:first-child{width:auto}.wb-fold-table th,.wb-fold-table td{padding:5px 11px}.wf-project-row{background:var(--peach,#f4eee7)}.wf-name{display:flex;align-items:center;gap:6px;min-height:24px}.wf-toggle,.wf-spacer{width:23px;flex:none}.wf-toggle{height:22px;display:inline-flex;align-items:center;justify-content:center}.wf-project-name{color:var(--accent);font-weight:400;text-align:left}.wf-task-link{color:var(--project-blue);font-weight:400;text-align:left}.wf-project-name:hover,.wf-task-link:hover{text-decoration:underline}.wf-count{color:var(--muted);white-space:nowrap}.wf-task-name{padding-left:16px}.wf-subtask{padding-left:32px}.wb-fold-table .wb-progress{min-width:0;gap:6px}.wb-fold-table .progress-track{width:80px;flex:none}.wb-fold-table td.wf-due-soon{color:var(--accent);font-weight:600}
.wf-task-link.task-completed,.wf-task-link.task-completed:hover{text-decoration:line-through}</style>
