<script setup lang="ts">
import TaskDependencyBadge from './TaskDependencyBadge.vue'
import {sortTaskSiblings} from './task-order'
import ProjectTaskCheckbox from './ProjectTaskCheckbox.vue'
import {taskTotalDays,formatDays} from './workday-summary'
import {ref,computed} from 'vue'
import ProjectDateRange from './ProjectDateRange.vue'
import type {ProjectTask} from './project-api'
const props=defineProps<{tasks:ProjectTask[];allTasks?:ProjectTask[];parent?:string|null;level?:number;collapsed?:boolean;manage?:boolean}>()
defineEmits<{edit:[task:ProjectTask];view:[task:ProjectTask]}>()
const closed=ref<string[]>([])
const roots=computed(()=>sortTaskSiblings(props.tasks.filter(t=>props.parent?t.parentId===props.parent:!t.parentId||!props.tasks.some(p=>p.id===t.parentId)),props.tasks))
const hasChildren=(id:string)=>props.tasks.some(t=>t.parentId===id)
</script>
<template><template v-for="task in roots" :key="task.id"><tr class="tree-task"><td><div class="tree-name" :style="{paddingLeft:((level||0)*16+16)+'px'}"><button v-if="hasChildren(task.id)" class="text-link tree-toggle" :aria-label="`展开或收起任务 ${task.title}`" :aria-expanded="!collapsed&&!closed.includes(task.id)" @click="closed=closed.includes(task.id)?closed.filter(id=>id!==task.id):[...closed,task.id]"><span class="fold-icon" aria-hidden="true">{{ collapsed||closed.includes(task.id)?'▸':'▾' }}</span></button><span v-else class="tree-spacer"></span><ProjectTaskCheckbox :task-id="task.id" :title="task.title" :state="task.state" /><button class="text-link tree-title" :class="{'task-completed':task.state==='已完成'}" @click="$emit('view',task)">{{ task.title }}</button><TaskDependencyBadge :task="task" :tasks="allTasks||tasks" /></div></td><td>{{ task.taskType||'未选择' }}</td><td>{{ task.owner||'—' }}</td><td class="tree-dates"><ProjectDateRange :start="task.start" :end="task.due" /></td><td>{{ taskTotalDays(task)==null?'—':formatDays(taskTotalDays(task)!) }}</td><td>{{ task.state }}</td><td><div class="tree-progress"><progress :value="task.progress" max="100" :aria-label="`${task.title}进度`"></progress><span>{{ task.progress }}%</span></div></td><td class="task-actions-cell"><button v-if="manage||task.canEdit" class="tree-edit" @click="$emit('edit',task)">{{ manage?'编辑任务':'更新进度' }}</button><span v-else class="muted" title="只有项目负责人、管理员或该任务执行人可修改">仅查看</span></td></tr><ProjectTaskTree v-if="hasChildren(task.id)&&!collapsed&&!closed.includes(task.id)" :tasks="tasks" :all-tasks="allTasks||tasks" :parent="task.id" :level="(level||0)+1" :manage="manage" @edit="$emit('edit',$event)" @view="$emit('view',$event)" /></template></template>
<style scoped>.tree-task td{padding:4px 8px;border-bottom:1px solid var(--line);vertical-align:middle;font-size:14px}.tree-name{display:flex;align-items:center;gap:6px;min-height:24px}.tree-title{font-size:14px;font-weight:500;text-align:left;overflow-wrap:anywhere;padding:0;border:0;background:transparent;color:var(--project-blue)}.tree-title:hover{color:var(--project-blue);text-decoration:underline}.tree-toggle{display:inline-flex;align-items:center;justify-content:center;width:23px;height:24px;padding:0;border:0;background:transparent;color:inherit;flex:none}.tree-spacer{width:23px;flex:none}.task-actions-cell{position:sticky;right:0;z-index:1;background:var(--surface,#fff);box-shadow:-1px 0 0 var(--line)}.tree-edit{white-space:nowrap;border:1px solid var(--line);border-radius:5px;background:white;padding:5px 8px;font:inherit;color:var(--accent)}.tree-dates{white-space:nowrap}.tree-progress{display:flex;align-items:center;gap:6px}.tree-progress progress{width:65px;height:6px;accent-color:var(--accent)}.tree-progress span{white-space:nowrap}.tree-title.task-completed,.tree-title.task-completed:hover{text-decoration:line-through}</style>
